### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by hbast**
fixed link under [3]

### CODE REVIEW

**Comment by bradfa** [comment]
Thanks for the fix but in my dev branch this has already been fixed.  It just hasn't yet been pushed up to Arnd so my linaro branch hasn't been updated as that tracks Arnd's upstream.

See SHA: 98f6d249af48dac2ac0276446d3b54adad8590df

**Comment by hbast** [comment]
Ah sorry, I did not notice your branch!

**Comment by bradfa** [comment]
That's OK, no worries.
But if you find anything else that needs fixing and want to send a patch / pull request, please feel free to.  Eventually, once I have something substantial to send up to Arnd, I'll send patches / pull request to him.

So far, my dev branch doesn't have that many changes from what's on linaro.

**Comment by hbast** [comment]
Ok,.. first of all I'll try to understand what to do with the results flashbench provides. I came across to flashbench while working on my RasPi and reading Arnd's article on lwn.net. So I made several test with my 32GB Transcend SDHC Card which can be found on http://pastebin.com/X8iYgB1z
What I got out of these results, is that my card has a blocksize of 4K. So now I have to find out, how to align my partions correctly...

**Comment by bradfa** [comment]
@aronadaal you should email your results to the flashbench-results mailing list.  From a quick look through your paste, it looks like you have 8 MiB erase blocks.

Running the `--open-au` tests will show how many linear open erase blocks (allocation units) the card can handle simultaneously, and if you use `--random` it'll show how many in a random access mode.  See other results on the list for clues on good sets of commands to run to test.

If you're looking to align partitions, see https://gist.github.com/1477240 (provided you have a mmc/sd reader in the computer doing the formatting).  Slight changes are needed to support SCSI type USB readers.  I have a script that accounts for either type, I'll try to gist it soon (remind me if I don't).  That script is for a Beaglebone, it needs 2 partitions, one FAT for the boot loader and 1 of any Linux type for the root file system.  I'm not familiar with the RPi, but use that as a guide.

**Comment by bradfa** [comment]
Updated script I spoke of: https://gist.github.com/3828860

**Comment by hbast** [comment]
thx for the script! It works fine for me and I did some filetransfer tests. But 9Mb/s or 11MB/s isn't what I've expected,...
Maybe you got some time and have a look at http://pastebin.com/eN6Hmgi1

I posted my results of the card on the mailing list. I think you already read the mail.

**Comment by bradfa** [comment]
11 MB/s is pretty good for most SD cards.  If you really expect more, you have to pay quite a bit more :)

If you try rerunning your test but with `bs=8M` that should write in 8 MiB chunks instead of 1 KiB chunks like you are with `bs=1024`.  That should up the speed to closer to what you saw in your flashbench results, around 17 MiB/sec.  17 MiB/sec is very good for SD cards.

The SDHC spec maxes out at 25 MB/sec (SI units, not 1024 base units) due to 50 MHz clock and 4 bit data bus.  If you get any where near to 25 MB/sec, now you're at the limit of the bus, not the card.  The UHS spec allows for some higher transfer rates on the bus but not that many hosts support it yet.  Plus, the cards are quite a bit more expensive usually.

`/dev/urandom` sometimes isn't very fast, depending on your system.  If you try `/dev/zero` that might give you better results.  Also, try using `oflag=direct` or `oflag=sync` to avoid the kernel buffering writes which can make the transfers appear faster than they really are.  But, if you use either of these, I'm not sure that `/dev/zero` or `/dev/urandom` will work as sources.  If you have a fast enough hard disk, first create a large file on there, then `dd` that file to the card with the `oflag` parameters.

**Pull request closed without merging**
