### PR TITLE
Updated README for readability

### PR DESCRIPTION
**Pull request by tukoz**
Adding some Markdown syntax. Correct link to linaro FlashSurvey.
TODO: Add some updated information as the original README was written back in 2011 and eg tools to manipulate partitions and filesystems give better (but not perfect) alignment automatically:
- [fdisk](https://www.cl.cam.ac.uk/cgi-bin/manpage?8%20fdisk) - [Default offset and alignments changed in 2.18](http://git.kernel.org/cgit/utils/util-linux/util-linux.git/commit/?id=40c7aaf3958c28b38772f38ee245b20afe3c1373)
- [mkdosfs](https://www.cl.cam.ac.uk/cgi-bin/manpage?8%20mkdosfs) - [Data structure alignment changed to cluster boundaries in 3.0.8](http://daniel-baumann.ch/gitweb/?p=software/dosfstools.git;a=commit;f=manpages/en/mkfs.fat.8;h=247ba068d4ceea886ca16c95ab4a8eb772dc4f7a)
- [mke2fs](https://www.cl.cam.ac.uk/cgi-bin/manpage?8%20mke2fs) - [Device geometry probing to allow metadata and block alignment optimisation added in 1.41.10](http://git.kernel.org/cgit/fs/ext2/e2fsprogs.git/commit/?id=9ed8e5fec226aa53634ed95cbeac736d90a518e5)
- [parted](https://www.cl.cam.ac.uk/cgi-bin/manpage?8%20parted) - [Device geometry probing added in 2.1](http://git.savannah.gnu.org/cgit/parted.git/commit/?id=1a176a1f397424cca933fb392f8ec86d65effa21)

### CODE REVIEW

**Comment by bradfa** [comment]
Sorry for the huge delay in responding to you.

I have no intention of using markdown for the README, it's not what Arnd's upstream did and I don't intend to change that.

But I have incorporated your change for the Flash Card Survey wiki link into my dev branch, thank you for that!  My dev branch holds my changes, the linaro branch is intended to be a mirror of Arnd's upstream.

See: https://github.com/bradfa/flashbench/commit/39121d23567f623a9417ff932bde860e4da2fad5

**Comment by tukoz** [comment]
Hey! Thanks for reviewing my commits; glad you could make it. Flashbench has proven valuable to test my flash-memory based devices and setting them up faster as well as more durable (I run a simple NAS on a 16 gig usb key, various Maintenance/testing live USB tools and got busted in a Chromebook).

Question: Is the mailing list still in use as of today?

**Comment by bradfa** [comment]
On 07/13 10:20, Cyrille Laloy wrote:

> Question: Is the mailing list still in use as of today?

Yes, the mailing list is still active, although there isn't as much
traffic these days.  There's currently 17 subscribers to the list.

I'll likely have some newer eMMC parts to test in the near future which
I'll post results from.

**Comment by tukoz** [comment]
Thank you for clarifying about the ml. And yeah, it'll be nice to see (and add to) eMMC tests.

**Pull request closed without merging**
